services:
  - type: web
    name: django-blog-filter-api
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn blog_api_filter.wsgi:application --bind 0.0.0.0:$PORT"
    autoDeploy: true

    envVars:
      - key: DEBUG
        value: False

      - key: SECRET_KEY
        generateValue: true

      - key: DATABASE_URL
        fromDatabase:
          name: blogdb
          property: connectionString

databases:
  - name: blogdb
    plan: free
